### ISSUE TITLE
paypal pending payment invoice

### ISSUE THREAD

**Issue by peralchimia** [sprankhub/Spranks_AutomaticInvoices#1]
hello, thank you for your extention! I've a issue on my magento site with your project: the system sent an automatic invoice at the end of the ordering process, when on the checkuot you click on confirm your order...so you are redirect to paypal, but the invoice is sent also if you do not pay. It would be correct to send the invoice after the payment is complete not when the status is panding payment...can you help me  to fix this issue...becouse i'm having invoices without payment...
thank you!
Alessio

**Comment by sprankhub** [comment]
I do not think that it is correct to wait for a payment before the invoice is created and sent. What if you offer "invoice" as a payment option? Then the customer expects an invoice before he pays.

I am not a lawyer and it probably depends on your terms and agreements, but I would expect that the customer needs to pay his order as soon as he presses the "buy" button on your page. Hence, if his PayPal payment fails, he has to pay again anyway.

**Comment by peralchimia** [comment]
Hello, sorry maybe i've not understood the nature of you extension...you say:
"This extension can invoice and send invoice mails for orders PAYED with specified payment methods automatically."
but if you do not pay, for any reasons, the status of the order is pending payment, so is better to specify not FOR ORDERS PAYED but for order confirmed...it's more realistic... because if you use external payment method as paypal the system change the status to payed only for succesfull payment.
I do not know where do you live, but in Italy the invoice is sent after the payment, and this need to have the same date of the payment, and the invoice number is sequential respecting the chronological order.
thank you for your answer, so i know the issue it's not a bug of the extension but the extension is no good for italian customer, maybe it's good for your country.
regards, Alessio

**Comment by sprankhub** [comment]
As already described, if a customer uses the payment option "invoice", the customer expects to get an invoice, which he can then pay, no? That is at least the way how it works in Germany...

If your requirements are exactly like you described, then my extension is not the right choice for you, sorry. But I do not see any chance to reliably check if an order is payed anyway. The state/status of an order is quite a vague thing in Magento. Only an invoice can reliably marked as payed in Magento afaik.
